### ISSUE TITLE
Support for diminishing ALL except "xyz"?

### ISSUE THREAD

**Issue by ianyepan** [myrjola/diminish.el#11]
I'd love to diminish all minor modes except for a few like projectile and lsp-mode. Is there a way to do so? It would save the user so many lines of "diminish" keywords.

**Comment by myrjola** [comment]
Hi! Does this work for you:

```
    (require 'seq)
    (dolist (mode
             (seq-filter
              (lambda (elt) (not (seq-contains '(projectile-mode lsp-mode) elt)))
              minor-mode-list))

      (diminish mode))
```

It should diminish everything except projectile-mode and lsp-mode.

**Comment by ianyepan** [comment]
Thanks for the snippet! It works after start-up, but if I enter a buffer that triggers a minor mode being loaded, I'd have to call the `dolist` again, since diminish didn't detect this new minor mode when it did the cleanup. An example would be that I have emmet-mode triggered after web-mode is loaded, then the snippet would not hide emmet-mode. Is there a hook that I can bind the snippet to, so that whenever all minor modes of a buffer is finish loading I can envoke the snippet?

So far I've tried binding your snippet to after-init-hook and prog-mode-hook. But since modes like emmet or rainbow loads slower than the snippet being called, they would still not be correctly hidden.

My attempt so far:
```emacs-lisp
(use-package diminish
  :config
  (defun diminish-most-modes ()
    "Hide most minor modes except the ones listed here."
    (interactive)
    (dolist (mode
             (seq-filter
              (lambda (elt)
                (not (seq-contains '(projectile-mode
                                     lsp-mode
                                     flycheck-mode)
                                   elt)))
              minor-mode-list))
      (diminish mode)))

  (add-hook 'after-init-hook #'diminish-most-modes)
  (add-hook 'prog-mode-hook #'diminish-most-modes))
```

**Comment by myrjola** [comment]
You could try adding the function to `after-load-functions`. All of those functions are run when a library is loaded https://www.gnu.org/software/emacs/manual/html_node/elisp/Hooks-for-Loading.html.

```
(require 'seq)

(defun diminish-most-modes (unused)
  (dolist (mode
           (seq-filter
            (lambda (elt) (not (seq-contains '(projectile-mode lsp-mode) elt)))
            minor-mode-list))

    (diminish mode)))

(add-to-list 'after-load-functions 'diminish-most-modes)
```

**Comment by ianyepan** [comment]
@myrjola By using the variable `after-load-functions`, it works perfectly! I have one last concern: according to the documentation you linked to, the snippet is essentially **"asking for `diminish-most-modes` to be executed each time Emacs loads a library"**, do you think this will cost a lot in terms of performance and redundant execution? Or does this little function with diminish most likely not matter?

**Comment by myrjola** [comment]
You should not experience any performance impact when editing files. The libraries should only be loading once per library, so performance impact occurs only during startup and when loading new libraries e.g. when opening a new file format that lazy-loads relevant libraries.

**Comment by ianyepan** [comment]
I see.
I've been trying it out for the past couple hours and I have to say that the performance decrease during start-up or opening new files is **not** noticeable. I'll close this issue, and thanks again for the reply.
