### ISSUE TITLE
Unable to diminish apheleia-mode

### ISSUE THREAD

**Issue by avatar-lavventura** [myrjola/diminish.el#19]
I have tried:

```lisp
(apheleia-global-mode +1)
(diminish 'apheleia-mode)
(diminish 'apheleia-global-mode)
```

------------------

But I keep seeing `Apheleia` at the bottom line. 

`Driver.py   ~/program/user Git:dev (home) [Py]  Top (15, 0)  Apheleia------------`

Would it be possible to suppress it?

**Comment by avatar-lavventura** [comment]
Solved in here: https://emacs.stackexchange.com/a/70379/18414

**Comment by vincentbernat** [comment]
Humm, this does not seem really solved. You need to save once to get Apheleia minor mode diminished. The SE answer seems to suggest that Apheleia does something unexpected. Maybe it could be fixed?
