### ISSUE TITLE
How to hide google-this-mode with Diminish?

### ISSUE THREAD

**Issue by ReneFroger** [myrjola/diminish.el#2]
Thanks for sharing this package! I use the https://github.com/Malabarba/emacs-google-this
The strange thingy is that Dminish works well for all modes, but I never managed to hide Google-this-mode in the statusbar.

Examples:

```
(with-eval-after-load 'google-this-mode
(google-this-mode . ""))


(diminish 'google-this-mode)


(with-eval-after-load 'google-this-mode
    (diminish 'google-this-mode))
```

The Google mode is still popping up in my mode line. Another suggestion?

**Comment by myrjola** [comment]
Works for me with `GNU Emacs 25.1.4 (x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G1004)) of 2016-09-13`.

After `M-x google-this-mode` I see `Google` in the modeline.

![image](https://cloud.githubusercontent.com/assets/36122/19017665/0d056b56-8843-11e6-9177-e586dc4e5e89.png)!

After evaluating `(diminish 'google-this-mode)` the "Google" indicator disappears.

![image](https://cloud.githubusercontent.com/assets/36122/19017674/27dbdf78-8843-11e6-8066-05bd4926099e.png)

The variable that determines what indicators to show in the modeline is `minor-mode-alist`. What values do you get for `(assq 'google-this-mode minor-mode-alist)`? Here's my results:

```
(diminish-undo 'google-this-mode)

(assq 'google-this-mode minor-mode-alist)
;; Result: (google-this-mode google-this-modeline-indicator)

(diminish 'google-this-mode)

(assq 'google-this-mode minor-mode-alist)
;; Result: (google-this-mode "")
```

**Comment by alezost** [comment]
> (with-eval-after-load 'google-this-mode
>     (diminish 'google-this-mode))

The feature is called `google-this`, so it should be:

``` elisp
(with-eval-after-load 'google-this
  (diminish 'google-this-mode))
```

P.S.: not tested as I don't use neither `google-this-mode`, nor `diminish` :smile: (I use [dim](https://github.com/alezost/dim.el) instead)

**Comment by ReneFroger** [comment]
Thanks myrjola for your review. I tested it, and I guess it has something with the order of loading packages. I decided to load Google This first, then load Diminish afterwards.

**Comment by ReneFroger** [comment]
Thanks myrjola for your review. I tested it, and I guess it has something with the order of loading packages. I decided to load Google This first, then load Diminish afterwards.

Thanks for all your help, it's appreciated!

**Comment by alezost** [comment]
@ReneFroger, the order doesn't matter, did you actually try to use this?:

``` elisp
(with-eval-after-load 'google-this
  (diminish 'google-this-mode))
```

I'm sure this is all that is needed (note again that the feature name is `google-this`, not `google-this-mode` as was in your example)
