### ISSUE TITLE
diminish holy-mode and smartparens-mode

### ISSUE THREAD

**Issue by ghost** [myrjola/diminish.el#3]
I'm trying to diminish the `holy-mode` (from Spacemacs) and `smartparens-mode` but it doesn't work. However, other modes I tried to diminish so far working perfectly like `merlin`, `projectile`.

Do you know what happens with the `holy-mode` and `smartparens-mode`?

Below is the code that I use:

```
  ;; smartparens
  (eval-after-load "smartparens-mode" '(diminish 'smartparens-mode " ⒫"))

  ;; holy-mode
  (eval-after-load "holy-mode" '(diminish 'holy-mode " ⓗ"))
  (with-eval-after-load 'holy-mode '(diminish 'holy-mode " ⓗ"))
```

Thanks for taking your time to look at my issue! :-)

**Comment by myrjola** [comment]
Spacemacs has its own implementation of `diminish` called `spacemacs|diminish`. If a mode has already been diminished with `spacemacs|diminish` you can't diminish it with `diminish`. What you're looking for is:

```
(spacemacs|diminish holy-mode " ⓗ")
```

**Comment by ghost** [comment]
Thanks a lot. You're right!
